version: '3.1'
services:
  verisafe:
    image: verisafe:v4
    ports:
    - "8000:8000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: verisafe
      POSTGRES_PASSWORD: verisafe
      POSTGRES_DB: verisafe
    ports:
    - "5431:5432"