version: '3.1'

services:
  verisafe:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Path to the Dockerfile for the verisafe service
    ports:
      - "${VERISAFE_PORT}:${VERISAFE_PORT}"
    depends_on:
      - postgres
    networks:
      - app_network
    env_file:
      - .env  # Specify the .env file

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5431:5432"
    networks:
      - app_network
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # Mount initialization scripts

networks:
  app_network:
    driver: bridge
