// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: awards.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVibePointTransaction = `-- name: CreateVibePointTransaction :one
INSERT INTO vibe_point_transactions (
  awarded_user, points_awarded, reason, created, modified_at
) VALUES ( 
  $1, $2, $3, NOW(), NOW()
)
RETURNING id, awarded_user, points_awarded, reason, created_at, modified_at
`

type CreateVibePointTransactionParams struct {
	AwardedUser   pgtype.UUID `json:"awarded_user"`
	PointsAwarded int32       `json:"points_awarded"`
	Reason        *string     `json:"reason"`
}

func (q *Queries) CreateVibePointTransaction(ctx context.Context, arg CreateVibePointTransactionParams) (VibePointTransaction, error) {
	row := q.db.QueryRow(ctx, createVibePointTransaction, arg.AwardedUser, arg.PointsAwarded, arg.Reason)
	var i VibePointTransaction
	err := row.Scan(
		&i.ID,
		&i.AwardedUser,
		&i.PointsAwarded,
		&i.Reason,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
