// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: login_credentials.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserCredentials = `-- name: GetUserCredentials :one
SELECT user_id, username, email, password, last_login FROM login_info
WHERE username = $1
OR email = $2
OR user_id = $3 LIMIT 1
`

type GetUserCredentialsParams struct {
	Username string      `json:"username"`
	Email    pgtype.Text `json:"email"`
	UserID   uuid.UUID   `json:"user_id"`
}

func (q *Queries) GetUserCredentials(ctx context.Context, arg GetUserCredentialsParams) (LoginInfo, error) {
	row := q.db.QueryRow(ctx, getUserCredentials, arg.Username, arg.Email, arg.UserID)
	var i LoginInfo
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.LastLogin,
	)
	return i, err
}
