// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	carbon "github.com/dromara/carbon/v2"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Campus struct {
	ID              uuid.UUID   `json:"id"`
	CampusName      string      `json:"campus_name"`
	CampusAddress   pgtype.Text `json:"campus_address"`
	City            pgtype.Text `json:"city"`
	County          pgtype.Text `json:"county"`
	ZipCode         pgtype.Text `json:"zip_code"`
	Country         pgtype.Text `json:"country"`
	EstablishedYear pgtype.Int4 `json:"established_year"`
	PictureUrl      pgtype.Text `json:"picture_url"`
	IsActive        pgtype.Bool `json:"is_active"`
}

type Credential struct {
	UserID     uuid.UUID     `json:"user_id"`
	Password   *string       `json:"password"`
	LastLogin  carbon.Carbon `json:"last_login"`
	CreatedAt  carbon.Carbon `json:"created_at"`
	ModifiedAt carbon.Carbon `json:"modified_at"`
}

type LoginInfo struct {
	UserID          uuid.UUID     `json:"user_id"`
	Username        string        `json:"username"`
	Email           pgtype.Text   `json:"email"`
	Password        *string       `json:"password"`
	LastLogin       carbon.Carbon `json:"last_login"`
	AdmissionNumber pgtype.Text   `json:"admission_number"`
}

type Permission struct {
	ID             int32         `json:"id"`
	PermissionName string        `json:"permission_name"`
	CreatedAt      carbon.Carbon `json:"created_at"`
	ModifiedAt     carbon.Carbon `json:"modified_at"`
}

type Role struct {
	ID          int32         `json:"id"`
	RoleName    string        `json:"role_name"`
	Description pgtype.Text   `json:"description"`
	CreatedAt   carbon.Carbon `json:"created_at"`
	ModifiedAt  carbon.Carbon `json:"modified_at"`
}

type RolePermission struct {
	RoleID       int32         `json:"role_id"`
	PermissionID int32         `json:"permission_id"`
	CreatedAt    carbon.Carbon `json:"created_at"`
	ModifiedAt   carbon.Carbon `json:"modified_at"`
}

type RolePermissionsView struct {
	RoleID         int32         `json:"role_id"`
	RoleName       string        `json:"role_name"`
	PermissionID   int32         `json:"permission_id"`
	PermissionName string        `json:"permission_name"`
	CreatedAt      carbon.Carbon `json:"created_at"`
	ModifiedAt     carbon.Carbon `json:"modified_at"`
}

type User struct {
	ID         uuid.UUID     `json:"id"`
	Username   string        `json:"username"`
	Firstname  string        `json:"firstname"`
	Othernames string        `json:"othernames"`
	Phone      pgtype.Text   `json:"phone"`
	Email      pgtype.Text   `json:"email"`
	Gender     pgtype.Text   `json:"gender"`
	Active     pgtype.Bool   `json:"active"`
	NationalID pgtype.Text   `json:"national_id"`
	CreatedAt  carbon.Carbon `json:"created_at"`
	ModifiedAt carbon.Carbon `json:"modified_at"`
}

type UserRole struct {
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     int32         `json:"role_id"`
	CreatedAt  carbon.Carbon `json:"created_at"`
	ModifiedAt carbon.Carbon `json:"modified_at"`
}

type Userprofile struct {
	UserID            uuid.UUID     `json:"user_id"`
	AdmissionNumber   pgtype.Text   `json:"admission_number"`
	Bio               pgtype.Text   `json:"bio"`
	VibePoints        pgtype.Int4   `json:"vibe_points"`
	DateOfBirth       pgtype.Date   `json:"date_of_birth"`
	ProfilePictureUrl pgtype.Text   `json:"profile_picture_url"`
	Campus            pgtype.UUID   `json:"campus"`
	LastSeen          carbon.Carbon `json:"last_seen"`
	CreatedAt         carbon.Carbon `json:"created_at"`
	ModifiedAt        carbon.Carbon `json:"modified_at"`
}
