// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: referals.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReferal = `-- name: CreateReferal :one
INSERT INTO user_referals ( referring_user, referred_user, created_at, modified_at)
VALUES ( $1, $2, NOW(), NOW())
RETURNING id, referring_user, referred_user, created_at, modified_at
`

type CreateReferalParams struct {
	ReferringUser pgtype.UUID `json:"referring_user"`
	ReferredUser  pgtype.UUID `json:"referred_user"`
}

func (q *Queries) CreateReferal(ctx context.Context, arg CreateReferalParams) (UserReferal, error) {
	row := q.db.QueryRow(ctx, createReferal, arg.ReferringUser, arg.ReferredUser)
	var i UserReferal
	err := row.Scan(
		&i.ID,
		&i.ReferringUser,
		&i.ReferredUser,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
